import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [recommendations, setRecommendations] = useState([])

  useEffect(() => {
    
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>A main!</main>

      <footer>A footer!</footer>
    </div>
  )
}
